<a href="https://colab.research.google.com/github/Ludmi0611/Proyecto-Analisis-Meteorologico/blob/main/An%C3%A1lisis_de_Datos_Meteorol%C3%B3gicos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Análisis de Datos Meteorológicos

Este proyecto consiste en analizar un conjunto de datos meteorológicos utilizando Pandas y NumPy. El objetivo es aplicar las técnicas de manipulación de arrays, tratamiento de datos faltantes, y análisis estadísticos básicos en un conjunto de datos.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
ruta=pd.read_csv('/content/drive/MyDrive/Udemy- Python para data science/dia 8/datos_meteorologicos.csv')

# 1.Creación de un DataFrame con los datos extraídos del archivo datos_meteorologicos.csv

In [ ]:
df = pd.DataFrame(ruta)
df

Fecha  Temperatura  Precipitación    Humedad
0     01/01/2010    17.440675      10.957482  52.384637
1     02/01/2010    25.759468       5.315628  30.633530
2     03/01/2010    20.138169      15.317706  41.496715
3     04/01/2010    17.244159      13.151008  90.684704
4     05/01/2010    11.182740      16.413667  22.116422
...          ...          ...            ...        ...
5105  24/12/2023    -9.554692      12.700998  50.094533
5106  25/12/2023     2.837831       5.475686  92.456057
5107  26/12/2023    29.873597       4.615012  18.362847
5108  27/12/2023          NaN            NaN        NaN
5109  28/12/2023    37.308043       7.330510  50.646211

[5110 rows x 4 columns]

# 2. Observaciones iniciales de los datos con Pandas

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5110 entries, 0 to 5109
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Fecha          5110 non-null   object 
 1   Temperatura    4855 non-null   float64
 2   Precipitación  4855 non-null   float64
 3   Humedad        4855 non-null   float64
dtypes: float64(3), object(1)
memory usage: 159.8+ KB


In [ ]:
df.describe()

Temperatura  Precipitación      Humedad
count  4855.000000    4855.000000  4855.000000
mean     14.889296       9.901604    54.359061
std      14.440466       5.801842    26.096345
min      -9.996378       0.003008    10.014980
25%       2.651777       4.756907    31.866578
50%      14.693274       9.853698    54.254478
75%      27.381451      14.966997    77.029500
max      39.998201      19.999559    99.996582

In [ ]:
df.isna()

Fecha  Temperatura  Precipitación  Humedad
0     False        False          False    False
1     False        False          False    False
2     False        False          False    False
3     False        False          False    False
4     False        False          False    False
...     ...          ...            ...      ...
5105  False        False          False    False
5106  False        False          False    False
5107  False        False          False    False
5108  False         True           True     True
5109  False        False          False    False

[5110 rows x 4 columns]

# 3. Convierto las columnas de DataFrame en arrays de NumPy.

In [ ]:
temperatura = df['Temperatura'].to_numpy()
precipitacion = df['Precipitación'].to_numpy()
humedad = df['Humedad'].to_numpy()

temperatura

array([17.4406752 , 25.75946832, 20.1381688 , ..., 29.87359717,
               nan, 37.30804318])

# 4. Identifico los datos faltantes en los arrays, y reemplazo por el promedio de los valores del respectivo array.

In [ ]:
temp_nulo = np.isnan(temperatura)
prec_nulo = np.isnan(precipitacion)
humed_nulo = np.isnan(humedad)

temp_nulo

array([False, False, False, ..., False,  True, False])

In [ ]:
promedio_temp = np.nanmean(temperatura)
promedio_prec = np.nanmean(precipitacion)
promedio_humed = np.nanmean(humedad)


In [ ]:
temperatura[temp_nulo]= promedio_temp
precipitacion[prec_nulo]= promedio_prec
humedad[humed_nulo]= promedio_humed

temperatura

array([17.4406752 , 25.75946832, 20.1381688 , ..., 29.87359717,
       14.88929572, 37.30804318])

# 5. Realizo un análisis estadístico básico

Temperatura promedio

In [ ]:
temp_promedio = np.nanmean(temperatura)
temp_promedio

14.889295723531713

Total de precipitaciones

In [ ]:
precipitaciones_total = np.sum(precipitacion)
precipitaciones_total

50597.19438939993

Máxima humedad registrada

In [ ]:
max_humedad = np.max(humedad)
max_humedad

99.99658156071747

Fecha más calurosa

In [ ]:
# Encuentro la fila con la temperatura máxima
fila = df.loc[df['Temperatura'].idxmax()]
fila

Fecha            12/07/2017
Temperatura       39.998201
Precipitación     10.351345
Humedad           43.689543
Name: 2749, dtype: object

In [ ]:
fecha_calurosa= fila['Fecha']
fecha_calurosa

'12/07/2017'

Fecha más fría

In [ ]:
fila2 = df.loc[df['Temperatura'].idxmin()]
fila2

Fecha            23/07/2020
Temperatura       -9.996378
Precipitación      6.491993
Humedad           37.880461
Name: 3856, dtype: object

In [ ]:
fecha_fria = fila2['Fecha']
fecha_fria

'23/07/2020'

# 6. Exportar los resultados a un nuevo archivo CSV


In [ ]:
resultados = pd.DataFrame({
    'Metricas': ['Temperatura Promedio', 'Precipitacion Total', 'Humedad Máxima', 'Día mas Caluroso', 'Día mas Frío'],
    'Valor': [temp_promedio, precipitaciones_total, max_humedad, fecha_calurosa, fecha_fria]
})

resultados.to_csv('/content/drive/MyDrive/Udemy- Python para data science/dia 8/Resultados análisis meteorológicos.csv', index=False)